### ISSUE TITLE
критика 

### ISSUE THREAD

**Issue by dest4590** [SetScript/redact#1]
говно, удаляй

**Comment by SetScript** [comment]
нахуй иди

**Comment by dest4590** [comment]
Что там такое? Сунул голову в кусты
Кто это такой? У него лицо кисы
У него смешная шляпка и котьи усы
Он как Смурфик, лапка
На нём белые трусы

Эй, Шайлушай
Шайлу-Шайлу-Шайлушай
Эй, Шайлушай
Самый добрый Шайлушай
Эй, Шайлушай
Шайлу-Шайлу-Шайлушай
Эй, Шайлушай
Вот такой вот Шайлушай

А, в траве жить непросто
Кузнечики, птицы — повсюду опасно
Коль вышел, надо бороться
Идти, невзирая на сотни препятствий
Идти, не бояться и тогда есть шансы
Воздастся нам, братцы, пойду через лес
Тут лисы-красавцы, жуки-оборванцы
Но если пройду, то отпразднуем танцем
В деревне моей и в кругу родных
Зелёных полей и таких же, как мы

[Припев]
Эй, Шайлушай
Шайлу-Шайлу-Шайлушай
Эй, Шайлушай
Самый добрый Шайлушай
Эй, Шайлушай
Шайлу-Шайлу-Шайлушай
Эй, Шайлушай
Вот такой вот Шайлушай

Эй, Шайлушай
Шайлу-Шайлу-Шайлушай
Эй, Шайлушай
Самый добрый Шайлушай
Я живу в траве
Да, я добрый, любопытный
Эй, гигант, привет!
Дай мне, пж, нитку
Все грибы на мне
Я хочу корзинку
У меня лишь один грех
Я убил улитку

Эй, Шайлушай
Шайлу-Шайлу-Шайлушай
Эй, Шайлушай
Самый добрый Шайлушай
Эй, Шайлушай
Шайлу-Шайлу-Шайлушай
Эй, Шайлушай
Вот такой вот Шайлушай
